-- import the module that lets us generate lists and dicts that use character names
local characters = require "scripts.character_lists"
local props = require "scripts.prop_lists"

local function split_string(--[[required]]string_to_split, --[[optional]]delimiter)
	-- function to imitate the string.split() function from python
	-- split a string into a list of substrings, separating based on
	-- a given delimiter.  Splits by spaces by default
	-- @param string_to_split: string, it's the string that's being split into a list
	-- @param delimiter: (OPTIONAL) string, it's the substring that's being used to identify
	--					 where to separate the input string, defualt is " " (space)
	-- returns: a list of strings

	-- define the default value for the delimiter argument
	delimiter = delimiter or "%S+"
	
	-- split apart the words in the name for the currently selected arrow button
	local string_list = {}

	-- iterate over the substrings in the input string
	for word in string_to_split:gmatch(delimiter) do
		
		-- add the current word to the list of substrings
		table.insert(string_list, word)
	end

	-- return the split string
	return string_list
end


local function get_debug_options()
	-- function to return a dictionary mapping debug options to whether they're active or not
	-- debug options' statuses get stored locally by the main menu GUI and are
	-- then communicated to characters at the start of the night when the GO
	-- button is clicked
	-- return: a dict, keys are all strings and values are all booleans

	return { interval_timer = false,
	hitbox_viewer = false,
	radar = false,
	highlight_clickables = false,
	highlight_doors = false,
	unlimited_power = false,
	remove_ditto = false}
	
end


local function get_debug_list()
	-- function to return a list of the debug options 
	-- return: a dict, keys are all strings and values are all booleans

	return { "interval_timer",
	"hitbox_viewer",
	"radar",
	"highlight_clickables",
	"highlight_doors",
	"unlimited_power",
	"remove_ditto"}

end


function init(self)

	-- initialize by setting all of the menu elements' textures to use the atlas
	gui.set_texture(gui.get_node("go button"), "main_menu")
	gui.set_texture(gui.get_node("kaizo button"), "main_menu")

	-- assign all of the menu elments their proper animations
	gui.play_flipbook(gui.get_node("go button"), "go button")
	gui.play_flipbook(gui.get_node("kaizo button"), "kaizo button")
	gui.play_flipbook(gui.get_node("add 1 to all button"), "add 1 to all button")
	gui.play_flipbook(gui.get_node("set all 0 button"), "set all 0 button")
	gui.play_flipbook(gui.get_node("set all 20 button"), "set all 20 button")

	-- initialize the dictionary of prop URLs
	self.prop_urls = props.get_prop_urls()

	-- initialize the dictionary of prop locations
	self.prop_locations = props.get_prop_locations()

	-- initialize the dictionary of character URLs
	self.character_urls = characters.get_character_urls()

	-- initialize the dictionary tracking characters' levels
	self.character_levels = characters.get_character_levels()

	-- initialize the maximum character level
	self.max_level = 20

	-- generate a list of names for all characters' slates on the menu
	self.character_slates = characters.get_character_slates()
	print("character slates list obtianed")
	-- initialize a variable to indicate which character's slate is being
	-- hovered over by the mouse
	self.selected_node = "none"

	-- generate a list of names for all characters' arrow buttons to change their levels
	self.character_arrows = characters.get_character_arrows()
	print("character arrows list obtained")
	-- initialize a variable to indicate which arrow button is currently being clicked
	self.selected_arrow = "none"
	-- initialize a variable to indicate if an arrow button is currently in the down position
	self.is_arrow_down = false
	-- initialize a variable to indicate if an arrow button is on its cooldown between every
	-- level added to a character's AI (having this boolean lets us slow down how quickly levels
	-- get added if you hold down an arrow button)
	self.is_arrow_cooldown = false

	-- initialize variables to track the x and y coordinates of the mouse cursor
	-- (allows functions to access the mouse coordinates without crashing if there are no inputs)
	self.mouse_x = 0
	self.mouse_y = 0
	
	-- initialize the y-coordinates for the main menu's arrow buttons for when they're
	-- presseed down and when they're released
	self.hi_arrow_position = -15
	self.low_arrow_position = -20

	-- initialize a variable to track if the menu is in the middle of starting the night
	-- so the go button can't be spam clicked to mess with the fade to black animation
	-- or to mess with coordinating the variables and messages at the start of the night
	self.is_starting_night = false

	-- initialize a variable to track whether kaizo mode is on or off
	self.is_kaizo = false
	print("self.is_kaizo initialized")

	-- initialize the score
	self.score = 0

	-- attempt to either read the high score off the save file or default to 0
	local save_path = sys.get_save_file("poke_ucn", "saved_score")
	self.hi_score = sys.load(save_path).hi_score or 0

	-- initialize the dictionary of all debug options and their on/off statuses
	self.debug_statuses = get_debug_options()

	-- initialize a list of all debug options' names and the variable tracking which option
	-- is currently selected
	self.debug_list = get_debug_list()
	self.selected_debug = "none"

	-- disable the red overlay that shows when kaizo mode is active
	gui.set_enabled(gui.get_node("red overlay"), false)

	-- disable the fade to black effect that plays when the night starts
	gui.set_enabled(gui.get_node("fade to black"), false)

	-- iterate over all character slates' nodes by iterating over
	-- all indicies in the list of nodes and accessing nodes by their index
	for curr_idx = 1, #self.character_slates do
		-- assign a variable to make calling on the current slate easier
		local curr_slate = self.character_slates[curr_idx]
		
		-- reset all character slates to their unselected sprites
		-- print("iterating, hit: " .. curr_slate)
		gui.set_texture(gui.get_node(curr_slate), "main_menu")
		gui.play_flipbook(gui.get_node(curr_slate), "character menu slate")
	end

	-- print("end of menu_handler.gui_script init function")
end

function final(self)
	-- Add finalization code here

	-- release input focus when finalizing
	msg.post(".", "release_input_focus")
	-- print("menu handler has released input focus")
	
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	print("menu handler received a message: " .. message_id .. " from sender:" .. sender)
	
	-- check if the message says to show the GUI
	if message_id == hash("show") then
		
		-- post messages to the system to enable this object
		-- and to acquire input focus
		msg.post(".", "enable")
		msg.post(".", "acquire_input_focus")
		-- print("enabled and acquired input focus")

	-- check if the message says to hide the GUI
	elseif message_id == hash("hide") then
		
		-- post messages to the system to disable this object
		-- and release input focus
		msg.post(".", "disable")
		msg.post(".", "release_input_focus")
		-- print("disabled and released input focus")

	elseif message_id == hash("update_hi_score") then

		-- update the high score
		self.hi_score = message.hi_score
		gui.set_text(gui.get_node("high score"), tostring(self.hi_score))

		-- save the high score
		-- make a file path to save the high score to
		-- local save_file = sys.get_save_file("poke_ucn", "saved_score")
		-- attempt to save the high score and report if something went wrong
		-- if not sys.save(save_file, { hi_score = self.hi_score }) then
			-- print("URGENT: could not save high score " .. self.hi_score .. " to " .. " poke_ucn/saved_score under the path of " .. save_file)
		-- end
		
	end

end


local function get_active_debug_options(self)
	-- function to make a list of all debug options that are on (their status is true in
	-- the self.debug_options dictionary)
	-- @param self: this allows the object calling the function to reference
	--				its own attributes as defined/updated in other functions
	-- @return: a list of strings

	-- initialize the list to be returned
	local active_debug_options = {}

	-- iterate over the keys and values of the debug options list
	for debug_option, status in pairs(self.debug_statuses) do
		
		-- check if the current debug option is turned on
		if status then
			
			-- insert the name of the current debug option into the list of active debug options
			table.insert(active_debug_options, debug_option)

		end
	end

	-- return the list of debug options that are turned on
	return active_debug_options
end


local function start_night(self)
	-- function that's called when the Go button on the main menu is
	-- clicked to start the night
	print("Start_night() ran")

	-- print("Go button clicked: changing sprite and switching to office")

	-- update the variable tracking whether the go button has been clicked
	-- so this function can't be called multiple times by spamming the GO button
	self.is_starting_night = true

	-- try to animate the go button being highlighted
	gui.play_flipbook(gui.get_node("go button"), "go button highlighted")

	-- play the animation for the screen fading to black
	gui.set_enabled(gui.get_node("fade to black"), true)
	gui.play_flipbook(gui.get_node("fade to black"), "fade to black")
	-- print("Animation progressed!")

	-- reset the office and cameras for the start of a new night
	msg.post("office_GUI", "new_night")
	msg.post("office_GUI", "update_debug", { debug_options = get_active_debug_options(self) })
	msg.post("/office/office", "new_night")
	msg.post("camera_GUI", "new_night", {is_tera = self.is_kaizo} )
	msg.post("camera_GUI", "update_debug", { debug_options = get_active_debug_options(self), 
											 character_levels = self.character_levels })
	msg.post("/camera/camera", "new_night")
	msg.post("game_over", "update_challenge_mode", { is_tera = self.is_kaizo})
	msg.post("win_screen", "update_scores", { curr_score = self.score, 
											  hi_score = self.hi_score, 
											  is_tera = self.is_kaizo, 
											  debug_options = get_active_debug_options(self) })

	-- tell all of the characters that a new night is starting
	for curr_character, curr_level in pairs(self.character_levels) do
		print(curr_character .. " type: " .. type(curr_character))
		msg.post(self.character_urls[curr_character], 
				 "new_night", 
				{ ai_level = curr_level, is_tera = self.is_kaizo, 
				  hitboxes_enabled = self.debug_statuses.hitbox_viewer})
	end

	-- tell all of the props that the night is starting
	for curr_prop, curr_url in pairs(self.prop_urls) do
		-- tell the prop to define itself with its name and location
		msg.post(curr_url, "define_self", { name = curr_prop, url = curr_url, location = self.prop_locations[curr_prop], animation = curr_prop } )
		-- tell the prop that the night is starting
		msg.post(curr_url, "new_night")
	end
	
	-- wait before posting a message to the controller script to switch to the office 
	-- and unload the menu
	timer.delay(0.4, false, function() 
		-- disable the fade to black visual effect
		gui.set_enabled(gui.get_node("fade to black"), false)
		
		-- post a message to the controller to unload the main menu and load the office
		msg.post("controller", "show_office")
		msg.post("controller", "show_camera")

		-- ALSO reset the go button after the screen has changed (relevant if the player returns
		-- to the main menu) (for some reason this ALL has to be inside the timer)
		gui.play_flipbook(gui.get_node("go button"), "go button") 

		-- reset the variable tracking if this function is running
		self.is_starting_night = false
	end)
end


local function get_clicked_node(nodes_list, mouse_x, mouse_y)
	-- function that iterates over all nodes' names to idenitfy which 
	-- of the nodes on the GUI is touching the mouse cursor

	-- iterate over a list of the given node names from the list
	-- yes, this is the lua version of "for item in list:"
	for __, curr_node in ipairs(nodes_list) do

		-- check if the current one is being selected with pick_node()
		if gui.pick_node(gui.get_node(curr_node), mouse_x, mouse_y) then

			-- return the name of the node that's at the mouse's x and y coords
			-- print("curr node: " .. curr_node .. " mouse_x: " .. mouse_x .. " mouse_y: " .. mouse_y)
			return curr_node

		end
	end

	-- this only runs if no node was clicked, return that no node was clicked 
	-- (this avoids returning a nil value)
	return "none"
end


local function update_selected_debug(self, mouse_x, mouse_y)
	-- function to determine which debug option on the main menu
	-- the mouse is hovering over
	-- @param self: this allows the object calling the function to reference
	--				its own attributes as defined/updated in other functions
	-- @param mouse_x: float (maybe an int), the x coordinate of the mouse cursor
	-- @param mouse_y: float, the y coordinate of the mouse cursor
	-- @return: nothing, just modifies object attributes

	-- initialize a variable to get the name of which arrow button the mouse cursor is
	-- currently hovering over, if it isn't hovering over one, this will be "none"
	local new_selected_debug = get_clicked_node(self.debug_list, mouse_x, mouse_y)

	-- check if the currently selected arrow is the same as the one that was selected
	-- last time this function ran
	if (self.selected_debug ~= new_selected_debug) then
		-- this runs if the debug option button the mouse is hovering over is NOT the same 
		-- as the last time this ran
		-- print("==========Selected Debug Option Changed===========")
		-- print("Mouse was hovering over: " .. self.selected_debug)
		-- print("Mouse currently hovering over: " .. new_selected_debug)
		
		-- update the variable tracking what arrow button is currently selected
		self.selected_debug = new_selected_debug

	end
end


local function toggle_debug_option(self)
	-- function to toggle the debug option whose button is being hovered over
	-- @param self: this allows the object calling the function to reference
	--				its own attributes as defined/updated in other functions
	-- @return: none, just updates a boolean stored in a dict

	-- make sure the debug option is actually in the dictionary
	if self.debug_statuses[self.selected_debug] ~= nil then

		print("Previous debug status: " .. self.selected_debug .. " : " .. tostring(self.debug_statuses[self.selected_debug]))

		-- toggle the status of the currently selected debug option
		self.debug_statuses[self.selected_debug] = not self.debug_statuses[self.selected_debug]
		print("Status is now: " .. tostring(self.debug_statuses[self.selected_debug]))
		
		-- now to update the text node for the debug option to indicate if it's on
		-- initialize the text indicating the debug option's status
		local debug_button_text = gui.get_text(gui.get_node(self.selected_debug))

		-- initialize the text_to_display variable
		local text_to_display

		-- check if the selected debug option is on
		if self.debug_statuses[self.selected_debug] then

			-- since the debug option is on, cross off the checkbox to be displayed
			text_to_display = string.gsub(debug_button_text, "_", "X")

		else

			-- since the debug option is off, blank out the checkbox to be displayed
			text_to_display = string.gsub(debug_button_text, "X", "_")
			
		end

		-- update the text node for the selected debug option
		gui.set_text(gui.get_node(self.selected_debug), text_to_display)

		print("Updated debug option: " .. text_to_display)
		
	end

end

local function update_selected_slate(self, mouse_x, mouse_y)
	-- function to determine if the character slate that the mouse is currently hovering over
	-- is the same as one that was previously being hovered over.
	-- if these aren't the same, then the old node needs to be reset to its unselected
	-- sprite and the new one needs to switch to its selected/highlighted sprite
	-- @return: nothing, just updates self.selected_node
	
	-- check if the node the mouse is currently touching is the same 
	-- as on the previous input
	print(self.character_slates)
	local new_selected_node = get_clicked_node(self.character_slates, mouse_x, mouse_y)

	-- check if the previously selected node is the same as the previous one
	if self.selected_node ~= new_selected_node then
		-- this only runs if the node the mouse is touching ISN'T the same as the last 
		-- time this ran. This means the previously selected node needs to no longer
		-- be highlighted and the new node needs to be highlighted

		-- check if the previously selelected/hovered-over node was "none", as would
		-- be the case if the mouse wasn't over any character slate
		if self.selected_node ~= "none" then
			-- since the previously-selected node was a character slate, we can tell it
			-- to switch to its unhighlighted sprite without crashing
			gui.play_flipbook(gui.get_node(self.selected_node), "character menu slate")

		end

		-- independently from that first check, we have to also check if the node the
		-- mouse is currently touching is one of the character slates to avoid
		-- an error if we tell it to switch to its highlighted sprite
		if new_selected_node ~= "none" then
			-- now we can tell the newly-selected character slate to be highlighted
			-- without an error
			gui.play_flipbook(gui.get_node(new_selected_node), "character menu slate highlighted")

		end

		-- update the variable tracking the node currently touching the mouse
		self.selected_node = new_selected_node
		
	end
end


local function toggle_kaizo(self)
	-- function to toggle whether kaizo mode is on/off and to 
	-- update the UI to reflect kaizo mode being on or off
	-- @param self: this allows the object calling the function to reference
	--				its own attributes as defined/updated in other functions
	-- @return: nothing, just modifies object attributes

	-- update the variable indicating kaizo mode
	self.is_kaizo = not (self.is_kaizo)
	print("updated is_kaizo to " .. tostring(self.is_kaizo))

	-- toggle the red background
	gui.set_enabled(gui.get_node("red overlay"), self.is_kaizo)

	-- change the sprite for the button depending on if the mode is being turned on or off
	if self.is_kaizo then
		-- this runs if kaizo mode is now turned on
		
		-- set the master ball to its colored sprite
		gui.play_flipbook(gui.get_node("master ball"), "Master ball")
		
		-- set the kaizo mode button to its highlighted sprite
		gui.play_flipbook(gui.get_node("kaizo button"), "kaizo button highlighted")

		-- then delay for 0.1 seconds before switching to its selected (darker) sprite
		timer.delay(0.1, false, function() 
			gui.play_flipbook(gui.get_node("kaizo button"), "kaizo button selected")
		end)

	else
		-- this runs if kaizo mode is now turned off
		
		-- set the master ball to its grayscale sprite
		gui.play_flipbook(gui.get_node("master ball"), "Master ball grayscale")

		-- set the kaizo mode button to its highlighted sprite
		gui.play_flipbook(gui.get_node("kaizo button"), "kaizo button highlighted")

		-- then delay for 0.1 seconds before switching to its greyed-out sprite
		timer.delay(0.1, false, function() 
			gui.play_flipbook(gui.get_node("kaizo button"), "kaizo button")
		end)
		
	end
	
end


local function set_character_level(self, character_name, new_level)
	-- function to set a character's AI level to a specified value
	-- @param self: this allows the object calling the function to reference
	--				its own attributes as defined/updated in other functions
	-- @param character_name: string, the name of the character whose level is being updated
	-- @param new_level: int, the new AI level the character is being set to
	-- @return: nothing, just modifies a value in self.character_levels (a dict)

	-- print("attempting to update " .. character_name .. "'s level")
	-- print(self.character_levels[character_name])

	-- check if the named character is in the dictionary of character levels
	if self.character_levels[character_name] ~= nil then

		-- set the character's level to the specified value
		self.character_levels[character_name] = new_level
		-- print(character .. "'s new level is: " .. self.character_levels[character])

	end
end


local function add_to_character_level(self, character_name, value_to_add)
	-- function to add a specified number to a character's AI value
	-- @param self: this allows the object calling the function to reference
	--				its own attributes as defined/updated in other functions
	-- @param character_name: string, the name of the character whose level is being updated
	-- @param value_to_add: int, the number being added to the character's AI level
	-- @return: nothing, just modifies a value in self.character_levels (a dict)

	-- print("attempting to update " .. character_name .. "'s level")
	-- print(self.character_levels[character_name])

	-- check if the named character is in the dictionary of character levels
	if self.character_levels[character_name] ~= nil then

		-- set the character's level to the specified value
		self.character_levels[character_name] = self.character_levels[character_name] + value_to_add
		-- print(character .. "'s new level is: " .. self.character_levels[character])

		-- change the score to match the change in level
		self.score = self.score + value_to_add

		-- check if we just set the character's level above the maximum allowed level
		if self.character_levels[character_name] > self.max_level then
			-- set the level back down to 20
			self.character_levels[character_name] = self.max_level

			-- lower the score back down
			self.score = self.score - value_to_add

		elseif self.character_levels[character_name] < 0 then
			-- check if we just set the character's level below 0
			-- if we did, bring it back up to 0
			self.character_levels[character_name] = 0

			-- bring the score back up
			self.score = self.score - value_to_add
			
		end

	end
end


local function update_level_sprite(self, character_name)
	-- function to update the sprite displaying a given character's
	-- AI level
	-- @param self: this allows the object calling the function to reference
	--				its own attributes as defined/updated in other functions
	-- @param character_name: string, the name of the character whose level is
	-- 						  being displayed
	-- @return: nothing, just tells a node to switch sprites

	-- print("attempting to update " .. character_name .. "'s level")
	-- print(self.character_levels[character_name])

	-- check if the named character is in the dictionary of character levels
	if self.character_levels[character_name] ~= nil then
		-- print(character_name .. " found!")

		-- grab the sprite displaying the named character's level
		local sprite_to_update = gui.get_node(character_name .. " level")
		-- print("Was able to find the node displaying " .. character_name .. "'s level!")

		-- assign a variable to the character's current level for readability
		local new_level = self.character_levels[character_name]
		-- print(character_name .. "'s new level is " .. new_level)

		-- change the sprite to display the new value for the AI level
		gui.play_flipbook(sprite_to_update, tostring(new_level))

		-- update the score to match the change in AI level
		gui.set_text(gui.get_node("score"), self.score)
		-- print("Successfully updated " .. character_name .. "'s level")

		-- attempt to update the character's icon to be greyscale or not
		-- assign a variable to track the name of the node for the character's icon
		local character_icon_node = gui.get_node(character_name .. " icon")
		-- check if the character's level is 0
		if new_level ~= 0 then

			-- assign a variable to the name of the non-greyscale sprite for the icon
			local colored_icon = character_name .. " icon"
			
			-- if the character's level isn't being changed to 0, make their icon not greyscale
			gui.play_flipbook(character_icon_node, colored_icon)

		elseif new_level == 0 then
			-- assign a variable to the name of the greyscale sprite for the icon
			local greyscale_icon = character_name .. " icon greyscale"

			-- if the character's level isn't being changed to 0, make their icon not greyscale
			gui.play_flipbook(character_icon_node, greyscale_icon)
		end
	end
end


local function add_one_all_button(self)
	-- function to to add 1 to all characters' levels and animate the sprite
	-- @param self: this allows the object calling the function to reference
	--				its own attributes as defined/updated in other functions
	-- @return: nothing, just modifies values in self.character_levels (a dict)
	
	-- update the sprite for the "add 1 to all" button to be highlighted
	gui.play_flipbook(gui.get_node("add 1 to all button"), "add 1 to all button highlighted")

	-- iterate through all characters in the dictionary of characters
	-- and their AI levels
	for character, level in pairs(self.character_levels) do
		-- add one to the current character's level
		add_to_character_level(self, character, 1)

		-- update the sprite displaying the current character's level
		update_level_sprite(self, character)
	end

	-- reset the button to its un-highlighted sprite after 0.1 seconds
	timer.delay(0.1, false, function() 
		gui.play_flipbook(gui.get_node("add 1 to all button"), "add 1 to all button")
	end)
end


local function set_all_twenty_button(self)
	-- function to to set all characters' levels to 20 and animate the sprite
	-- @param self: this allows the object calling the function to reference
	--				its own attributes as defined/updated in other functions
	-- @return: nothing, just modifies values in self.character_levels (a dict)

	-- update the sprite for the "set all 20 button" button to be highlighted
	gui.play_flipbook(gui.get_node("set all 20 button"), "set all 20 button highlighted")

	-- iterate through all characters in the dictionary of characters
	-- and their AI levels
	for character, level in pairs(self.character_levels) do
		-- set the current character's level to 20
		set_character_level(self, character, 20)

		-- update the score
		self.score = 400

		-- update the sprite displaying the current character's level
		update_level_sprite(self, character)
	end

	-- reset the button to its un-highlighted sprite after 0.1 seconds
	timer.delay(0.1, false, function() 
		gui.play_flipbook(gui.get_node("set all 20 button"), "set all 20 button")
	end)
end


local function set_all_zero_button(self)
	-- function to to set all characters' levels to 0 and animate the sprite
	-- @param self: this allows the object calling the function to reference
	--				its own attributes as defined/updated in other functions
	-- @return: nothing, just modifies values in self.character_levels (a dict)

	-- update the sprite for the "set all 0 button" button to be highlighted
	gui.play_flipbook(gui.get_node("set all 0 button"), "set all 0 button highlighted")

	-- iterate through all characters in the dictionary of characters
	-- and their AI levels
	for character, level in pairs(self.character_levels) do
		-- set the current character's level to 0
		set_character_level(self, character, 0)

		-- update the score
		self.score = 0

		-- update the sprite displaying the current character's level
		update_level_sprite(self, character)
	end

	-- reset the button to its un-highlighted sprite after 0.1 seconds
	timer.delay(0.1, false, function() 
		gui.play_flipbook(gui.get_node("set all 0 button"), "set all 0 button")
	end)
end


local function reset_arrow_button(arrow_button_name)
	-- function to set an arrow button to its transparent sprite
	-- if it isn't selected anymore
	-- @param arrow_button_name: string, the name of the arrow button node that's having its
	-- 							 sprite reset
	-- @return: nothing, just changes a sprite

	-- split apart the words in the name for the currently selected arrow button
	local split_arrow_name = split_string(arrow_button_name)

	-- get the sprite for the arrow button's dimmed-out sprite (either "arrow up dim" 
	-- or "arrow down dim")
	local highlighed_sprite = split_arrow_name[2] .. " " .. split_arrow_name[3] .. " transparent"

	-- change the arrow button to its highlighted sprite
	gui.play_flipbook(gui.get_node(arrow_button_name), highlighed_sprite)

end


local function update_selected_arrow(self, mouse_x, mouse_y)
	-- function to determine which arrow button on the main menu
	-- the mouse is hovering over
	-- @param self: this allows the object calling the function to reference
	--				its own attributes as defined/updated in other functions
	-- @param mouse_x: float (maybe an int), the x coordinate of the mouse cursor
	-- @param mouse_y: float, the y coordinate of the mouse cursor
	-- @return: nothing, just modifies object attributes

	-- initialize a variable to get the name of which arrow button the mouse cursor is
	-- currently hovering over, if it isn't hovering over one, this will be "none"
	local new_selected_arrow = get_clicked_node(self.character_arrows, mouse_x, mouse_y)

	-- check if the currently selected arrow is the same as the one that was selected
	-- last time this function ran
	if (self.selected_arrow ~= new_selected_arrow) then
		-- this runs if the arrow button the mouse is hovering over is NOT the same 
		-- as the last time this ran
		-- print("==========Selected Arrow changed===========")
		-- print("Mouse was hovering over: " .. self.selected_arrow)
		-- print("Mouse currently hovering over: " .. new_selected_arrow)

		-- update the variable to indicate if an arrow button is being held down
		-- we want the button to be released when it's no longer being hovered over
		self.is_arrow_down = false
		-- print("=======")

		-- check if an arrow button was previously selected
		if self.selected_arrow ~= "none" then
			-- reset the sprite for the previously-selected arrow
			reset_arrow_button(self.selected_arrow)
		end
		

		-- update the variable tracking what arrow button is currently selected
		self.selected_arrow = new_selected_arrow

	end
end


local function animate_arrow_button(self, action, action_id)
	-- function to move an arrow button down when it's clicked and move it back when
	-- it's released
	-- @param self: this allows the object calling the function to reference
	--				its own attributes as defined/updated in other functions
	-- @param action: this seems to be a reference to the action being bound
	--				  by the high-level name assigned to the input being detected
	--				  and has attributes like action.released
	-- @param action_id: this is the name, in hash, of the input being detected
	-- return: nothing, just toggles whether self.is_arrow_down indicates that
	-- 		   an arrow button is being held down, and moves arrow buttons

	-- get the position of the selected arrow arrow
	-- local curr_arrow_position = gui.get_position(gui.get_node(self.selected_arrow))

	-- we need to check if the mouse is CURRENTLY hovering over an arrow button
	if not self.is_arrow_down then
		-- this only runs if the selected arrow button 
		
		-- split apart the words in the name for the currently selected arrow button
		local split_arrow_name = split_string(self.selected_arrow)

		-- get the sprite for the arrow button's highlighted sprite (either "arrow up 
		-- highlighted" or "arrow down highlighted")
		local highlighed_sprite = split_arrow_name[2] .. " " .. split_arrow_name[3] .. " highlighted"
		
		-- change the arrow button to its highlighted sprite
		gui.play_flipbook(gui.get_node(self.selected_arrow), highlighed_sprite)
		
		-- update the variable to indicate if an arrow button is being held down,
		-- so the code to make it move doesn't run more than once per click/release
		self.is_arrow_down = true

		-- Below is OLD CODE for when the arrow buttons moved
		-- calculate the new y-value for the clicked arrow button
		-- curr_arrow_position.y = self.low_arrow_position
		-- print("moved " .. self.selected_arrow .. " down to y= " .. curr_arrow_position.y)
		-- move the currently-selected arrow button to its low position (10 units below
		-- where it started)
		-- gui.animate(gui.get_node(self.selected_arrow), "position", curr_arrow_position, vmath.vector({1}), 0.01)

	-- check if mouse 1 has been released or if the mouse cursor is no longer over
	-- the currently-selected arrow button
	elseif action.released or not gui.pick_node(gui.get_node(self.selected_arrow), self.mouse_x, self.mouse_y) then
		-- split apart the words in the name for the currently selected arrow button
		local split_arrow_name = split_string(self.selected_arrow)

		-- get the sprite for the arrow button's dimmed-out sprite (either "arrow up dim" 
		-- or "arrow down dim")
		local highlighed_sprite = split_arrow_name[2] .. " " .. split_arrow_name[3] .. " transparent"

		-- change the arrow button to its highlighted sprite
		gui.play_flipbook(gui.get_node(self.selected_arrow), highlighed_sprite)

		-- update the variable to indicate if an arrow button is being held down,
		-- so the code to make it move doesn't run more than once per click/release
		self.is_arrow_down = false

		-- Below is OLD CODE for when the arrow buttons moved
		-- get the position of the selected arrow button
		-- local arrow_position = gui.get_position(gui.get_node(self.selected_arrow))
		-- get the new y-value (it needs to move back up)
		-- arrow_position.y = self.hi_arrow_position
		-- reset the previously-selected arrow to its initial position (10 units above
		-- where it was while it was clicked)
		-- gui.animate(gui.get_node(self.selected_arrow), "position", (arrow_position), vmath.vector({1}), 0.01)
		-- print("moved " .. self.selected_arrow .. " up to y= " .. arrow_position.y)

	end

end


local function click_to_change_level(self, action, action_id)
	-- function to change a character's AI level when their arrow button is clicked
	-- this function gets called when the mouse is hovering over an arrow button
	-- AND mouse 1 is being held down
	-- @param self: this allows the object calling the function to reference
	--				its own attributes as defined/updated in other functions
	-- @param action: this seems to be a reference to the action being bound
	--				  by the high-level name assigned to the input being detected
	--				  and has attributes like action.released
	-- @param action_id: this is the name, in hash, of the input being detected
	-- return: nothing, just changes self.character_levels (a dict)

	if self.is_arrow_down then
		-- split apart the words in the name for the currently selected arrow button
		local split_arrow_name = split_string(self.selected_arrow)
		
		-- now that we've split the arrow button's name, we'll grab the character's name from it
		-- for all arrow button nodes on the main menu, the first word is always the character
		-- whose AI that button adjusts
		local curr_character = split_arrow_name[1]
		print("Curr character: " .. curr_character)

		-- get the direction in which the AI level needs to be adjusted
		-- for all arrow button nodes, the third word is always "up" or "down"
		local level_change = split_arrow_name[3]

		-- here we're going to use the direction that we need to adjust the AI level
		-- to determine what number to add or subtract to the AI level when the arrow
		-- button is pressed
		if level_change == "up" then
			-- if the up arrow is pressed, the level needs to increase 1 at a time
			level_change = 1
		elseif level_change == "down" then
			-- if the down arrow is pressed, the level needs to decrease 1 at a time
			level_change = -1
		else
			-- this should't run, but this handles any weird cases where an arrow button
			-- isn't named properly or something
			level_change = 0
		end

		-- now change the character's AI level if the cooldown isn't active
		if not self.is_arrow_cooldown then
			add_to_character_level(self, curr_character, level_change)

			-- update the sprite indicating the current character's level
			update_level_sprite(self, curr_character)
			print(curr_character .. "'s level: " .. self.character_levels[curr_character])
			

			-- activate the cooldown for changing the character's level
			self.is_arrow_cooldown = true
			-- re-enable the ability to change the character's level after the cooldown
			timer.delay(0.1, false, function() self.is_arrow_cooldown = false end)
		end		
	end
end


local function quit_game()
	-- function to close the game when the quit button on the main menu is clicked
	-- this function gets called when the quit button is clicked
	-- @return: nothing, just exits
	
	-- highlight the quit game button
	gui.play_flipbook(gui.get_node("quit game button"), "quit game button highlighted")

	-- set a small delay to quitting the game
	timer.delay(0.2, false, function()
		-- exit the game with exit code 0 to indicate no issues
		sys.exit(0)
	end)
end


function on_input(self, action_id, action)
	-- function for input handling code
	-- @param self: this allows the object calling the function to reference
	--				its own attributes as defined/updated in other functions
	-- @param action_id: this is the name, in hash, of the input being detected
	-- @param action: this seems to be a reference to the action being bound
	--				  by the high-level name assigned to the input being detected
	--				  and has attributes like action.released
	-- @return: nothing, just a driver function

	-- assign a variable to track whether mouse1 has been clicked based on hash of the input
	-- coming in AND if the current input's button has been released
	local mouse1_clicked = action_id == hash("mouse1") and action.released

	-- update the variables tracking the mouse's coordinates
	-- check if the current input has an x coordinate for the mouse
	if action.x ~= nil then
		-- if the current input has an x coordinate, update the variable tracking the mouse's x coord
		self.mouse_x = action.x
	end
	-- check if the current input has a y coordinate for the mouse
	if action.y ~= nil then
		-- if the current input has a y coordinate, update the variable tracking the mouse's y coord
		self.mouse_y = action.y
	end

	-- check if mouse1 has been released and the mouse cursor is over the GO! button
	if mouse1_clicked and gui.pick_node(gui.get_node("go button"), action.x, action.y) then
		-- run the function to start the night if it's not already running
		if not self.is_starting_night then
			start_night(self)
		end

	-- check if mosue1 has been released and teh mouse cursor is over the kaizo mode button
	elseif mouse1_clicked and gui.pick_node(gui.get_node("kaizo button"), action.x, action.y) then
		-- run the function to start the night
		toggle_kaizo(self)

	elseif mouse1_clicked and gui.pick_node(gui.get_node("add 1 to all button"), action.x, action.y) then
		-- run the function to add 1 to all characters' levels and animate the sprite
		add_one_all_button(self)

	elseif mouse1_clicked and gui.pick_node(gui.get_node("set all 20 button"), action.x, action.y) then
		-- run the function to set all character levels to 20 and animate the sprite
		set_all_twenty_button(self)

	elseif mouse1_clicked and gui.pick_node(gui.get_node("set all 0 button"), action.x, action.y) then
		-- run the function to set all character levels to 0 and animate the sprite
		set_all_zero_button(self)

	elseif (action_id == hash("mouse1")) and (self.selected_arrow ~= "none") then
		-- run the function to move the arrow button while clicked
		animate_arrow_button(self, action, action_id)

		-- run the function to change the character's level while clicked
		click_to_change_level(self, action, action_id)

	elseif mouse1_clicked and self.selected_debug ~= "none" then
		-- run the function to toggle the selected debug option
		toggle_debug_option(self)

	elseif action_id == hash("d_key") and action.released then
		print("d key pressed")

	elseif mouse1_clicked and gui.pick_node(gui.get_node("quit game button"), action.x, action.y) then
		-- run the function to quit the game
		quit_game()

	end

	-- update which character slate on the menu is selected/being hovered over
	update_selected_slate(self, self.mouse_x, self.mouse_y)

	-- update which character's arrow button is being hovered over
	update_selected_arrow(self, self.mouse_x, self.mouse_y)

	-- update which debug option the mouse is hovering over
	update_selected_debug(self, self.mouse_x, self.mouse_y)

end

