function init(self)
	-- go to the center of the camera collection
	go.set_position(vmath.vector3(0, 0, 0))

	-- make sure to NOT have input focus
	msg.post(".", "release_input_focus")
	-- print("Mouse cursor: initialized and released input focus")
end

function final(self)
	-- release input focus in case it somehow doesn't happen before the game tries to close
	msg.post(".", "release_input_focus")
end


function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end


function on_message(self, message_id, message, sender)

	print("Mouse cursor: received message: " .. message_id .. " from " .. sender)
	if message_id == hash("new_night") then
		msg.post(".", "acquire_input_focus")
		-- print("Mouse cursor: acquired input focus")
		
	elseif message_id == hash("end_night") then
		msg.post(".", "release_input_focus")
		-- print("Mouse cursor: released input focus")
	end
end


function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:

	-- check if the mouse moved
	if action.x and action.y then
		-- move to the new mouse position
		go.set_position(vmath.vector3(action.x, action.y, 1))
		-- print("Mouse cursor: moved to: " .. action.x .. ", " .. action.y)
	end
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
