function init(self)
	-- initialize a variable for tracking the mouse's position
	-- needs to be initialized here because the update() function might check its value before
	-- an input is received from the mouse (so it can't be initialized in on_input())
	self.mouse_position = vmath.vector3(0, 0, 0)

	-- assign a variable to track the sprite's initial position
	self.init_position = go.get_position()
	-- print("Office initial position on load: " .. self.init_position)

	-- initialize a variable to know if the player is in the camera
	self.is_in_camera = false

	-- initialize a variable to know if the flashlight is on
	self.flashlight_is_on = false

	-- initialize a variable to know if the player has power
	self.has_power = true

	-- initialize variables to know if either door is open
	self.doors_closed = {
		right = false, 
		left = false
	}

	-- initialize variables to know if the doors are in their opening and closing animations
	self.doors_moving = {
		right = false,
		left = false
	}

	-- define the farthest left or right the office/object in office should move before stopping
	-- left and right bounds need to be relative to the object's starting position
	-- office starts at x = 790, left bound is 500 and right is 800
	self.left_bound = self.init_position.x - 290
	self.right_bound = self.init_position.x + 10

	-- define the fast and slow scroll speeds for the office
	self.fast_scroll = 10
	self.slow_scroll = 1.5

	-- define a multiplier that determines how slowly the player's POV slows down as they reach the edge of the office
	self.slowzone_multiplier = 0.1  -- the lower this is, the smoother the slowdown at the edge of the office is
	
end


local function reset_night(self)
	-- function to reset this object for the start of a night
	go.set_position(self.init_position)
	self.mouse_position.x = 640
	-- print("Office initial position on night start: " .. self.init_position)
	-- print("Office actual position on night start" .. go.get_position())

	-- reset the variable to know if the player is in the camera
	self.is_in_camera = false

	-- reset the variable to know if the flashlight is on
	self.flashlight_is_on = false

	-- make the flashlight sprite invisible
	msg.post("flashlight", "disable")

	-- initialize a variable to know if the player has power
	self.has_power = true

	-- resset the variables to know if either door is open
	self.doors_closed = {
		right = false, 
		left = false
	}

	-- reset the variables to know if the doors are in their opening and closing animations
	self.doors_moving = {
		right = false,
		left = false
	}

	-- reset the door's sprites
	sprite.play_flipbook("#left door", hash("left open"))
	sprite.play_flipbook("#right door", hash("right open"))

end


local function make_office_invisible()
	-- function to make the office invisible by moving it out of the renderable
	-- space.  Renderable space is between z = -1 and z = 1

	-- get the current position of the office collection
	local curr_position = go.get_position()

	-- calculate its new position (keeping x and y the same, but changing z
	-- to a large value outside the render distance)
	local new_position = vmath.vector3(curr_position.x, curr_position.y, 100)

	-- update the position
	go.set_position(new_position)

end


local function make_office_visible()
	-- function to make the office invisible by moving it into the renderable
	-- space.  Renderable space is between z = -1 and z = 1

	-- get the current position of the office collection
	local curr_position = go.get_position()

	-- calculate its new position (keeping x and y the same, but changing z
	-- to a value inside the renderable distance
	local new_position = vmath.vector3(curr_position.x, curr_position.y, 0)

	-- update the position
	go.set_position(new_position)

end


local function animate_door(selected_door, mode, self)
	-- function to play the animation for the selected door to open
	-- @param selected_door: str, indicates which door is being opened
	--						 expecteded to be "left" or "right"
	-- @param mode: str, indicates if the selected door is being opened or closed
	-- 				expected to be "opening" or "closing"
	-- @param self: allows the function to access variables stored as self.<variable_name>
	-- @return: nothing, just plays an animation

	-- tell the office gui whether this door is open or closed
	-- do this before updating the office's value so the usage
	-- changes as soon as the button is pressed
	msg.post("/office_GUI", "update_doors", { 
		selected_door = selected_door, 
		is_closed = not self.doors_closed[selected_door]
	})

	-- get the name of the door sprite that's being animated
	local door_to_animate = "#" .. selected_door .. " door"

	-- get the name of the animation to play
	local animation_to_play = selected_door .. " door " .. mode

	-- make a dictionary to map the mode (opening vs closing) to the words
	-- "open" or "closed" that are used in the file names for the door's
	-- open and closed sprites
	local finished_sprite_last_word = {
		opening = "open",
		closing = "closed"
	}

	-- get the name of the sprite the door will change to when finished
	local finished_sprite = selected_door .. " " .. finished_sprite_last_word[mode]

	-- set a flag to note that the door is playing an animtion
	self.doors_moving[selected_door] = true

	-- play the animation to open or close the door
	sprite.play_flipbook(door_to_animate, 
	hash(animation_to_play), 
	function()
		-- update the variable indicating whether the door is open or closed
		self.doors_closed[selected_door] = not self.doors_closed[selected_door]
		-- update the flag to indicate that the door is no longer in its animation
		self.doors_moving[selected_door] = false
		-- set the sprite of the door to its open or closed sprite
		sprite.play_flipbook(door_to_animate, hash(finished_sprite))
	end)
end


local function toggle_door(selected_door, self)
	-- function to toggle a specified door to be open or closed
	-- @param selected_door: str, indicates which door is being toggled
	-- @param self: allows this function to access values stored in self.<variable> variables
	-- @return: nothing, just updates an attribute stored in the GUI and sends a message

	-- initialzie a boolean to determine if the selected door is valid
	local is_valid_door = self.doors_closed[selected_door] ~= nil

	-- check if the selected door is currently opened or closed
	if is_valid_door and not self.doors_closed[selected_door] and not self.doors_moving[selected_door] then
		-- the door is currently open, so it needs to be closed
		-- play door closing animation
		animate_door(selected_door, "closing", self)

	elseif is_valid_door and self.doors_closed[selected_door] and not self.doors_moving[selected_door] then
		-- the door is currently closed, so it needs to be opened
		-- play door opening animation
		animate_door(selected_door, "opening", self)
	end
end


function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	print("Office received a message: " .. message_id .. " from sender:" .. sender)
	
	-- check if the message says to show the GUI
	if message_id == hash("show") then

		-- post messages to the system to enable this object
		-- and to acquire input focus
		msg.post(".", "enable")
		msg.post(".", "acquire_input_focus")

		-- check if the message says to hide the GUI
	elseif message_id == hash("hide") then

		-- post messages to the system to disable this object
		-- and release input focus
		msg.post(".", "disable")
		msg.post(".", "release_input_focus")

	elseif message_id == hash("new_night") then

		-- call the function that resets this game object and all its
		-- variables for the start of a new night
		reset_night(self)

	elseif message_id == hash("update_camera_status") then

		-- update the variable indicating whether the player is in the camera
		self.is_in_camera = message.is_in_camera

		-- check if the player is in the camera
		if self.is_in_camera then
			-- the office becomes invisible because the player is in the camera
			make_office_invisible()

		else
			-- the office becomes visible because the player isn't in the camera
			make_office_visible()
		end

	elseif message_id == hash("update_flashlight") then

		-- update the variable indicating whether the flashlight is on
		self.flashlight_is_on = message.flashlight_is_on

		-- check whether the flashlight is on
		if self.flashlight_is_on then
			-- make the flashlight sprite visible
			msg.post("flashlight", "enable")

		else
			-- make the flashlight sprite invisible
			msg.post("flashlight", "disable")
		end

	elseif message_id == hash("power_out") then
		-- this message tells the office that the player doesn't have power
		
		-- update the office's variable tracking if the player has power
		self.has_power = message.has_power

		-- force the doors open if they're closed
		-- iterate over the two doors
		for door, is_closed in pairs(self.doors_closed) do
			-- check if the door is open
			if is_closed then
				-- open the door
				toggle_door(door, self)

			end
				
		end

	end
	
end


function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	
	-- check if the mouse moved
	if action.x and action.y then
		-- update the mouse position variables
		self.mouse_position.x = action.x
		-- print("mouse_position.x: " .. self.mouse_position.x)
		self.mouse_position.y = action.y
	end
	
	-- if action_id == hash("mouse1") and action.pressed then
		-- print("Touch!")
	-- end
	
	if action_id == hash("d_key") and action.released and self.has_power then
		-- if the d key is pressed, the right door should be toggled
		toggle_door("right", self)

	elseif action_id == hash("a_key") and action.released and self.has_power then
		-- if the a key is pressed, the left door should be toggled
		toggle_door("left", self)
	end

end


local function update_office_position(self)
	-- function to update the position of the office collection
	-- get the current position of the office
	self.office_position = go.get_position()

	-- initialize the x value the office is about to move to
	local new_x = self.office_position.x
	local delta_x

	-- calculate how far the office sprite needs to move left/right
	-- mouse bounds are 640 +/- 160 or +/- 260
	if self.mouse_position.x < 300 and self.office_position.x < self.right_bound then
		-- mouse is far left, move the background sprite right quickly
		-- check if office sprite is close enough to the edge to warrant slowing down
		delta_x = self.slowzone_multiplier * (self.right_bound - self.office_position.x)
		if self.fast_scroll >= delta_x then
			-- office sprite should slow to a stop as the player POV reaches the edge of the background sprite
			-- the fast scroll speed is more extreme than delta_x, so use delta_x
			new_x = self.office_position.x + delta_x
		else
			-- player POV isn't near edge of office, don't worry about slowing the office sprite down
			new_x = self.office_position.x + self.fast_scroll
		end
		-- print("far left ran")
	elseif self.mouse_position.x < 480 and self.office_position.x < self.right_bound then
		-- mouse is middle left, move the background sprite right slowly
		-- check if office sprite is close enough to the edge to warrant slowing down
		delta_x = self.slowzone_multiplier * (self.right_bound - self.office_position.x)
		if self.slow_scroll >= delta_x then
			-- office sprite should slow to a stop as the player POV reaches the edge of the background sprite
			-- the slow scroll speed is more extreme than delta_x, so use delta_x
			new_x = self.office_position.x + delta_x
		else
			-- player POV isn't near edge of office, don't worry about slowing the office sprite down
			new_x = self.office_position.x + self.slow_scroll
		end
		-- print("middle left ran")
	elseif self.mouse_position.x > 1080 and self.office_position.x > self.left_bound then
		-- mouse is far right, move the background sprite left quickly
		-- check if office sprite is close enough to the edge to warrant slowing down
		delta_x = self.slowzone_multiplier * (self.left_bound - self.office_position.x)
		if (-1 * self.fast_scroll) <= delta_x then
			-- office sprite should slow to a stop as player POV reaches the edge of the background sprite
			-- fast scroll is more exterme than delta_x, so use delta_x
			new_x = self.office_position.x + delta_x
		else
			-- player POV isn't near the edge of the background sprite, so don't worry about slowing the office sprite down
			new_x = self.office_position.x - self.fast_scroll
		end
		-- print("far right ran")
	elseif self.mouse_position.x > 800 and self.office_position.x > self.left_bound then
		-- mouse is middle right, move the background sprite left slowly
		-- check if office sprite is close enough to the edge to warrant slowing down
		delta_x = self.slowzone_multiplier * (self.left_bound - self.office_position.x)
		if (-1 * self.slow_scroll) <= delta_x then
			-- office sprite should slow to a stop as player POV reaches the edge of the background sprite
			-- slow scroll speed is more extreme than delta_x, so use delta_x
			new_x = self.office_position.x + delta_x
		else
			-- player POV isn't near the edge of the background sprite, so don't worry about slowing the office sprite down
			new_x = self.office_position.x - self.slow_scroll
		end
		-- print("middle right ran")
	end
	-- print("Office: delta_x = " .. tostring(delta_x))
	-- print("Office: moving from x = " .. tostring(self.office_position.x) .. " to x = " .. tostring(new_x))
	-- print("Office: actual distance moved this frame was: " .. tostring(new_x - self.office_position.x))

	-- now that new x position is calculated, create a vector for the new position
	local new_position = vmath.vector3(new_x, self.office_position.y, self.office_position.z)
	-- print("new_position.: " .. new_position.x)
	-- print("new_position: " .. new_position)

	-- finally, update the office's position to the new value if the player is in the office
	go.set_position(new_position)
	
end


local function update_flashlight_position(self)
	-- function to update the position of the flashlight
	-- @param self: allows this function to access values stored in self.<variable> variables
	-- @return: nothing, just updates coordinates of a sprite

	-- apply an offset to the x and y coordinates of the mouse to account
	-- for the flashlight's position being relative to the office, which
	-- makes the flashlight be too far up and right based on the office's position
	local new_x = self.mouse_position.x - self.office_position.x
	local new_y = self.mouse_position.y - self.office_position.y

	-- define the new position for the flashlight
	local new_flashlight_pos = vmath.vector3(new_x, new_y, 0.9)

	-- set the position of the flashlight to the mouse position
	go.set_position(new_flashlight_pos, "flashlight")

end


function update(self, dt)
	-- Add update code here

	-- check if the player is in the camera
	if not self.is_in_camera then
		-- if the player is in the office, update the office's position
		update_office_position(self)
		-- move the flashlight to track with the mouse
		update_flashlight_position(self)
	end
end


function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
