-- import the shared helper functions
local cu = require "scripts.character_scripts.character_utils"

-- forward-declare the driver function so it can be mutually recurred by restart_path()
local driver

-- initialize AI level
go.property("level", 0)

-- initialize movement interval
go.property("interval", 15)

-- initialize if the player is in the challenge mode
go.property("is_tera", false)


function init(self)
	-- Add initialization code here

	-- initialize character name
	self.name = "dragapult"

	-- initialize his location on screen
	self.location = "Cam 06"

	-- initialize the lists of locations in this character's movement paths
	local left_path = {"Cam 04", "Cam 05", "Cam 09", "office"}
	local right_path = {"Cam 06", "Cam 11", "Cam 10", "office"}

	-- initialize the dictionary that will get used to get the character's location
	self.path = {
		left = left_path,
		right = right_path
	}

	-- initialize a variable tracking which path the character is on
	self.my_path = "right"

	-- initialize a variable tracking what step of his path he's on
	self.movement_step = 1

	-- initialize a variable tracking what evolutionary stage dragapult is on
	self.my_stage = 1

	-- initialize a dictionary mapping evolutionary stage to character name
	self.evolution_dict = {
		[1] = "dreepy",
		[2] = "drakloak",
		[3] = "dragapult"
	}

	-- initialize the dictionary mapping camera locations to his position on screen
	self.position_dict = {
		["Cam 04"] = vmath.vector3(234.0, -78.0, 0.0),
		["Cam 05"] = vmath.vector3(234.0, -78.0, 0.0),
		["Cam 06"] = vmath.vector3(234.0, -78.0, 0.0),
		["Cam 09"] = vmath.vector3(0, 0, 0.0),
		["Cam 10"] = vmath.vector3(-241.0, -141.0, 0.0),
		["Cam 11"] = vmath.vector3(0, 0, 0.0),
		["office"] = vmath.vector3(0, 0, 0.0)  -- note that this one doesn't matter because of the dummy sprite in the office
	}
	
	-- initialize the dictionary mapping camera locations to this character's sprite names
	self.sprite_dict = {
		dreepy = {
			["Cam 04"] = "dreepy",
			["Cam 05"] = "dreepy",
			["Cam 06"] = "dreepy",
			["Cam 09"] = "dreepy",
			["Cam 10"] = "dreepy",
			["Cam 11"] = "dreepy",
			["office"] = "dreepy"  -- note that this one doesn't matter because of the dummy sprite in the office
		},
		drakloak = {
			["Cam 04"] = "drakloak",
			["Cam 05"] = "drakloak",
			["Cam 06"] = "drakloak",
			["Cam 09"] = "drakloak",
			["Cam 10"] = "drakloak",
			["Cam 11"] = "drakloak",
			["office"] = "drakloak"  -- note that this one doesn't matter because of the dummy sprite in the office
		},
		dragapult = {
			["Cam 04"] = "dragapult",
			["Cam 05"] = "dragapult",
			["Cam 06"] = "dragapult",
			["Cam 09"] = "dragapult",
			["Cam 10"] = "dragapult",
			["Cam 11"] = "dragapult",
			["office"] = "dragapult"  -- note that this one doesn't matter because of the dummy sprite in the office
		},
	}

	-- initialize the dictionary mapping what camera dragpult is in to what flying animation to play
	self.animations = {
		["Cam 09"] = "dragapult left hall",
		["Cam 10"] = "dragapult right hall"
	}

	-- initialize values to track if the player is in the cameras
	self.is_in_camera = false

	-- initialize a value to track which camera is currently selected
	self.selected_camera = "Cam 01"

	-- initialize variables to know if either door is open
	self.doors_closed = {
		right = false, 
		left = false
	}

	-- initialize all timers
	self.movement_timer = timer.delay(0, false, function() print(self.name .. " move timer initialized") end)
	self.door_timer = timer.delay(0, false, function() print(self.name .. " door timer initialized") end)
	self.kill_timer = timer.delay(0, false, function() print(self.name .. " kill timer initialized") end)
	
	-- become invisible
	local curr_position = go.get_position()
	go.set_position(vmath.vector3(curr_position.x, curr_position.y, 100))

	-- initialize the variable tracking how much time this character should wait at the door
	self.max_door_time = 0.5

	-- initialize the variable tracking how much time this character has left to wait at the door
	self.remaining_door_time = self.max_door_time

	-- initialize the variable tracking how much time this character's kill timer has left on it
	self.remaining_kill_time = 5

	-- post a message to the instance of shared_character_code attached to this character
	-- informing it of which character's properties it should read
	msg.post(".", "define_self", { name = self.name })
	-- post a message to this chraacter's dummy object that sits in the office
	msg.post("/office/" .. self.name .. "_dummy", "define_self", { name = self.name })
end


local function set_sprite_scale(sprite_name, scale)
	-- function to scale this character's sprite in the x and y axes

	-- @param sprite_name: str, the url of the sprite being scaled
	-- @param scale: float, the multiplier on the sprite's width and height
	-- return: none

	-- handle the default value for the scale
	scale = scale or 5
	print("scaling " .. sprite_name .. " to " .. tostring(scale) .. "x scale")
	pprint("Sprite is at " .. go.get_position())

	go.set(sprite_name, "scale.x", scale)
	go.set(sprite_name, "scale.y", scale)

end


local function update_sprite(self)
	-- function to change the character's current sprite to whichever sprite is associated
	-- with the passed position
	-- @param self: allows this function to access self.<variable> variables
	-- @return: nothing, just changes sprites

	-- access the name of dreepy's current evolutionary stage
	local my_form = self.evolution_dict[self.my_stage]

	sprite.play_flipbook("#" .. self.name .. "_sprite", self.sprite_dict[my_form][self.location])
	-- print(name .. " just switched to sprite; '" .. sprite_dict[location] .. "' sprite at " .. location)

end


local function progress_movement(self)
	-- function to increment the character's movement step and update their
	-- location and position accordingly
	-- @param self: allows access to self.variable namespace
	-- @return: nothing 

	-- add 1 to the character's movement step
	self.movement_step = self.movement_step + 1

	-- update the character's location
	-- first access the correct sequence of rooms from self.path by keying it with
	-- the character's current path (self.my_path). Then access the right room in
	-- the list by keying it with the current step of this character's movement progression
	self.location = self.path[self.my_path][self.movement_step]
	print(self.name .. " moved to " .. self.location .. " along " .. self.my_path .. " path")

	-- tell the camera GUI to move this character's icon on the minimap (only visible if radar is on)
	msg.post("/camera_GUI", "move_character", 
		{char_name = self.name, 
		new_pos = self.location, 
		side = self.my_path
	})

	-- have this character check if they're visible
	msg.post(".", "update_visibility", {
		is_in_camera = self.is_in_camera, 
		camera_location = self.selected_camera, 
		location = self.location 
	})

	-- update this character's position on screen
	cu.update_coords(self.position_dict, self.location, go)
	
end


local function cancel_all_timers(self)
	-- function to cancel all of this character's timers
	-- @param self:
	-- @return: nothing, just cancels timers

	timer.cancel(self.movement_timer)
	timer.cancel(self.door_timer)
	timer.cancel(self.kill_timer)

end


local function restart_path(self)
	-- function to reset this character's movement path 

	-- pick a new path
	if self.my_stage == 1 then
		-- while in the unevolved dreepy form, this character always takes the right path
		self.my_path = "right"

	else
		-- once this character has evolved to either drakloak or dragapult, it can take either path
		local which_path = { "left", "right" }
		self.my_path = which_path[math.random(1,2)]
	end


	-- reset movement to step 0
	self.movement_step = 0
	-- go to the show stage (this function will increment the movement step to 1, which is the 
	-- show stage in both paths)
	progress_movement(self)
	-- recalculate this character's movement interval
	self.interval = cu.calculate_interval(self.non_random, math)
	msg.post(".", "update_displayed_time", {timer_name = "move_time", time_remaining = self.interval, is_running = true})
	-- update this character's sprite
	update_sprite(self)
	-- start the timer for the next movement
	self.movement_timer = timer.delay(self.interval, false, driver)

	print(self.name .. " just moved to " .. self.location .. "; New interval = " .. self.interval .. " sec")
end


local function leave_kill_state(self)
	-- function to handle this character leaving their kill state at the door
	-- Includes: cancelling door timer and kill timer, resetting position variable
	-- telling the dummy sprite in the office to become invisible, picking a new movement path, 
	-- and restarting the movement timer
	-- @param self:
	-- @return: nothing, just cancels a timer

	-- reset this character's kill timer
	self.remaining_kill_time = self.interval

	-- cancel this character's kill timer
	local result = timer.cancel(self.kill_timer)
	print("Leaving kill state, Result of cancelling " .. self.name .. "'s kill timer: " .. tostring(result))
	msg.post(".", "update_displayed_time", {timer_name = "kill_time", time_remaining = self.remaining_kill_time, is_running = false})

	-- cancel this character's timer to leave the door
	result = timer.cancel(self.door_timer)
	print("Leaving kill state, Result of cancelling " .. self.name .. "'s door timer: "  .. tostring(result))
	self.remaining_door_time = self.max_door_time
	msg.post(".", "update_displayed_time", {timer_name = "door_time", time_remaining = self.max_door_time, is_running = false})

	-- tell the dummy model in the office to become invisible
	msg.post("/office/" .. self.name .. "_dummy", "become_invisible")

	-- play the sound effect for this character leaving the door
	cu.play_directional_sound(sound, "#run_away", self.my_path, 1.00)

	-- use message passing to call the driver function because it's not defined yet at the time
	-- of this function getting compiled
	restart_path(self)

end


local function attack_door(self)
	-- function to check if the door is closed, and kills the player if not
	print("kill player ran, " .. self.my_path .. " door is closed: " .. tostring(self.doors_closed[self.my_path]))
	-- check if the door is closed
	if self.doors_closed[self.my_path] then
		leave_kill_state(self)
	else
		-- if the door isn't closed, start by playing the sound for the jumpscare
		cu.play_directional_sound(sound, "#" .. self.evolution_dict[self.my_stage] .. "_cry")

		-- send a message to the office gui to kill the player
		-- make the office GUI play the right evo stage's jumpscare animation and show the right tip after
		msg.post("/office_GUI", "kill_player", { character_name = self.evolution_dict[self.my_stage] })

		-- tell the dummy dragapult in the office to become invisible so it isn't visible during the jumpscare
		msg.post("/office/" .. self.name .. "_dummy", "become_invisible")
		
		-- cancel this character' timers
		cancel_all_timers(self)
	end
	
end


local function enter_kill_state(self)
	-- function to set a timer that is used to determine if this character
	-- should kill the player while this character is in the office
	-- also tells the dummy model in the office what coords to go to and tells it to become
	-- visible
	-- @param self:
	-- @return: none, sets timers and maps them to self.<variable> variables

	-- set the initial timer for the character appearing in the door before being a threat
	self.kill_timer = timer.delay(self.interval, false, attack_door)
	print("Entering kill state. timer_name: kill_time, time_remaining: " .. self.interval, ", is_running: true")
	msg.post(".", "update_displayed_time", {timer_name = "kill_time", time_remaining = self.interval, is_running = true})

	-- check if this character has evolved (drakloak and dragapult don't appear in the door)
	if self.my_stage == 1 then
		-- tell the dummy model in the office to become visible and which door to go to
		msg.post("/office/" .. self.name .. "_dummy", "become_visible", { my_path = self.my_path, sprite = self.evolution_dict[self.my_stage] })
	end

end


local function flying_attack(self)
	-- this is the kill state function for when this character is fully evolved
	-- cancels the kill timer, plays the animation of flying down the hall, and attempts to kill the player
	-- @param self: allows access to self.variable namespace
	-- @return: none

	local result = timer.cancel(self.kill_timer)
	print("Result of cancelling " .. self.name .. "'s kill timer in flying_attack(): " .. tostring(result))

	-- go to the center of the screen (go to z=0.1 to be in front of other actors in the hall)
	go.set_position(vmath.vector3(0, 0, 0.1))
	
	--- play the animation for flying down the hall, attack door on completion
	local animation_to_play = self.animations[self.location]
	set_sprite_scale("#" .. self.name .. "_sprite", 1)
	sprite.play_flipbook("#" .. self.name .. "_sprite", animation_to_play, function()

		attack_door(self)

		-- reset the scale on this character's sprite
		set_sprite_scale("#" .. self.name .. "_sprite")
	end)

end


function driver(self)
	-- driver function to be called by the timer

	-- move to the next location
	progress_movement(self)

	-- check if the character is in the office
	if self.location == "office" and not self.doors_closed[self.my_path] then
		-- run the function for the character to enter his kill state at the door
		print("Reached office, door was open. " .. self.name .. " entering kill state.")
		enter_kill_state(self)

		-- check if the door is closed when the character gets there
	elseif self.location == "office" and self.doors_closed[self.my_path] then
		-- set the door timer to leave the kill state if the door stays closed
		print("Reached office, door was closed. " .. self.name .. " starting door timer: " .. self.remaining_door_time .. " seconds")
		self.door_timer = timer.delay(self.remaining_door_time, false, leave_kill_state)
		msg.post(".", "update_displayed_time", {timer_name = "door_time", time_remaining = self.remaining_door_time, is_running = true})

	elseif self.movement_step == 3 and self.my_stage == 3 then
		-- this runs if this character is fully and is moving into a hallway
		
		-- check if the player is currently looking at the camera
		local player_location = cu.get_player_view(self.is_in_camera, self.selected_camera)
		if player_location == self.location then
			flying_attack(self)
		else
			-- set a longer than normal kill timer
			self.interval = cu.calculate_interval(self.non_random, math) * 3
			enter_kill_state(self)
		end

	else

		-- update this character's sprite
		update_sprite(self)

		-- update this character's movement interval
		self.interval = cu.calculate_interval(self.non_random, math)
		msg.post(".", "update_displayed_time", {timer_name = "move_time", time_remaining = self.interval, is_running = true})

		-- start the timer for the next movement
		-- this is recursive, but can be broken if the timer is canceled
		self.movement_timer = timer.delay(self.interval, false, driver)

	end

	print(self.name .. " just moved to " .. self.location .. "; New interval = " .. self.interval .. " sec")
end


local function set_door_timers(self)
	-- function to check if this character is in the office when a door is closed
	-- and either start or cancel this character's door timer (depending on whether
	-- the door this character is at has been opened or closed)

	-- make a couple booleans to shorten the next if statements
	local is_in_office = self.location == "office"
	local my_door_closed = self.doors_closed[self.my_path]

	print("set_door_timers ran: is_in_office = " .. tostring(is_in_office) .. " // my_door_closed = " .. tostring(my_door_closed))

	-- check if this character's door is closed
	if is_in_office and my_door_closed then
		-- this runs if the door this character is at was closed
		-- and only if the door timer isn't running

		-- start a counter to leave the door when it's been closed for half a second
		self.door_timer = timer.delay(self.remaining_door_time, false, leave_kill_state)
		msg.post(".", "update_displayed_time", {timer_name = "door_time", time_remaining = self.remaining_door_time, is_running = true})
		

		-- pause the kill timer
		local remaining_kill_time = cu.pause_timer(self.kill_timer, timer)

		-- check if the pause function returned a nil value
		if remaining_kill_time then
			-- only overwrite the remaining kill time if the kill timer was successfully paused
			self.remaining_kill_time = remaining_kill_time
			msg.post(".", "update_displayed_time", {timer_name = "kill_time", time_remaining = self.remaining_kill_time, is_running = false})
			
		end
		
		print("Door closed, result of cancelling " .. self.name .. "'s kill timer: " .. tostring(remaining_kill_time) .. ". " .. self.remaining_kill_time .. " sec left on it")

	elseif is_in_office and not my_door_closed then
		-- this runs if the door this character was at was opened while he was there
		-- and only if the kill timer has been paused

		-- pause the door timer
		local remaining_door_time = cu.pause_timer(self.door_timer, timer)

		-- check if the pause function returned a nil value
		if remaining_door_time then
			-- only overwrite the remaining door time if the pause function returned a number for the amount of time remaining
			self.remaining_door_time = remaining_door_time
			msg.post(".", "update_displayed_time", {timer_name = "door_time", time_remaining = self.remaining_door_time, is_running = false})
			
		end
		
		print("Door opened, result of cancelling " .. self.name .. "'s door timer: " .. tostring(remaining_door_time).. ". " .. self.remaining_door_time .. " seconds left on it")

		print("Restarting " .. self.name .. "'s kill timer with " .. self.remaining_kill_time .. " sec remaining.")
		-- resume the kill timer
		self.kill_timer = timer.delay(self.remaining_kill_time, false, attack_door)
		msg.post(".", "update_displayed_time", {timer_name = "kill_time", time_remaining = self.remaining_kill_time, is_running = true})
		

	end

end


function final(self)
	-- Add finalization code here
	cancel_all_timers(self) --putting this here so we don't accidentally cause memory leaks
end


local function start_night(self)
	-- function to reset all variables, timers, and sprites when the night starts
	-- @param self: 
	-- @return: nothing, just resets self.<variable> variables, sprites, position, and timers

	-- reset movement interval
	self.non_random = cu.calculate_nonrandom_interval(self.level, 8, 56)
	self.interval = cu.calculate_interval(self.non_random, math)
	print("Starting night. timer_name: move_time, time_remaining: " .. self.interval, ", is_running: " .. tostring(self.level ~= 0))
	msg.post(".", "update_displayed_time", {timer_name = "move_time", time_remaining = self.interval, is_running = self.level ~= 0})

	-- reset he variable tracking what step of his path he's on
	self.movement_step = 0

	-- reset values to track if the player is in the cameras
	self.is_in_camera = false

	-- reset the value to track which camera is currently selected
	self.selected_camera = "Cam 01"

	-- reset the variable tracking how much time this character should wait at the door
	self.max_door_time = 0.5

	-- reset the variable tracking how much time this character has left to wait at the door
	self.remaining_door_time = self.max_door_time

	-- reset the variable tracking how much time this character's kill timer has left on it
	self.remaining_kill_time = 5

	-- reset values that depend on if tera mode is on
	if self.is_tera then
		-- if the player is in the challenge mode, start the night as dragapult
		self.my_stage = 3

		-- and dragapult should start on a random path
		local which_path = { "left", "right" }
		self.my_path = which_path[math.random(1,2)]
		print("Dragapult started the night fully evolved and is on the " .. self.my_path .. " path.")
	else
		-- if the player isn't in the challenge mode, start the night as dreepy
		self.my_stage = 1

		-- and dreepy should start on the right path
		self.my_path = "right"

		print("Dreepy started the night unevolved and is on the " .. self.my_path .. " path.")
	end

	-- reset the scale of this character's camera sprite
	set_sprite_scale("#" .. self.name .. "_sprite")

	-- reset dragapult to the first camera in his movement path
	progress_movement(self)

	-- send the door time and kill time to the office GUI
	print("Starting night. timer_name: door_time, time_remaining: " .. self.max_door_time, ", is_running: false")
	msg.post(".", "update_displayed_time", {timer_name = "door_time", time_remaining = self.max_door_time, is_running = false})
	print("Starting night. timer_name: kill_time, time_remaining: " .. self.remaining_kill_time, ", is_running: false")
	msg.post(".", "update_displayed_time", {timer_name = "kill_time", time_remaining = self.remaining_kill_time, is_running = false})

	-- tell the camera GUI to move the this character icon on the minimap (only visible if radar is on)
	msg.post("/camera_GUI", "move_character", 
	{char_name = self.name, 
	new_pos = self.location, 
	side = self.my_path
	})

	-- reset variables to know if either door is open
	self.doors_closed = {
		right = false, 
		left = false
	}

	-- reset this character's position
	go.set_position(self.position_dict[self.location])

	-- become invisible for the start of the night
	msg.post(".", "update_visibility", {
		is_in_camera = self.is_in_camera, 
		camera_location = self.selected_camera, 
		location = self.location 
	})

	-- reset sprite
	update_sprite(self)

	-- check if this character's ai level is above 0
	if self.level ~= 0 then
		-- start the timer for a new night if the character's level is above 0
		print(self.name .. "'s initial interval: " .. self.interval)
		self.movement_timer = timer.delay(self.interval, false, driver)
	end
	

end


local function check_hallway(self)
	-- function to check three conditions under which dragapult should fly down the hall:
	-- 					A: Dragapult is fully evolved
	-- 					B: Dragapult is in a hallway
	-- 					C: The player is looking at dragapult
	-- @param self: allows access to self.variable namespace
	-- @return: nones

	-- check if the player is currently looking at the camera
	local player_location = cu.get_player_view(self.is_in_camera, self.selected_camera)
	local is_looking = player_location == self.location
	local fully_evolved = self.my_stage == 3
	local is_in_hall = self.movement_step == 3
	print(self.name .. " thinks player is looking at " .. player_location .. ", player is looking at me: " .. tostring(is_looking) .. ", am fully evolved: " .. tostring(fully_evolved) .. ", and am in hall: " .. tostring(is_in_hall))
	print(self.name .. "'s sprite is " .. go.get("#" .. self.name .. "_sprite", "size.x") .. " pixels wide and " .. go.get("#" .. self.name .. "_sprite", "size.y") .. " pixels tall")
	if is_looking and fully_evolved and is_in_hall then
		flying_attack(self)
	end
end


function on_message(self, message_id, message, sender)
	-- Add message-handling code here

	print(self.name .. " received a message: " .. message_id .. " from sender:" .. sender)

	if message_id == hash("new_night") then
		-- update this character's AI level
		self.level = message.ai_level
		print(self.name .. " set to level " .. self.level)

		-- reset the visibility on the dummy sprite in the office
		msg.post("/office/" .. self.name .. "_dummy", "become_invisible", { my_path = self.my_path })

		-- update whether the challenge mode is active
		self.is_tera = message.is_tera
		print(self.name .. " thinks tera mode is on: " .. tostring(self.is_tera))

		-- run the function that resets all timers and variables for the start
		-- of a new night
		start_night(self)

	elseif message_id == hash("end_night") then
		-- cancel all timers
		cancel_all_timers(self)

	elseif message_id == hash("evolve") and self.my_stage ~= 3 then
		-- since dreepy/drakloak isn't fully evolved right now, play the animation for evolving
		-- and add 1 to this character's evolutionary stage

		-- access the name of dreepy's current evolutionary stage
		local my_form = self.evolution_dict[self.my_stage]
		
		-- play animation of dreepy evolving into drakloak or drakloak evolving into pult
		sprite.play_flipbook("#" .. self.name .. "_sprite", my_form .. "_evolving", function()
			-- when the animation ends, add 1 to the evolution stage (do after so the right animation gets accessed)
			self.my_stage = self.my_stage + 1

			-- now switch to the correct sprite for the new form
			update_sprite(self)
		end)

		-- fly down the hallway to attack the player if this char is now fully evolved and was already
		-- in a hallway
		check_hallway(self)

	elseif message_id == hash("change_camera_location") then

		-- update this character's variable tracking what camera the player has selected
		self.selected_camera = message.new_cam

		-- update whether this character is visible
		msg.post(".", "update_visibility", {
			is_in_camera = self.is_in_camera, 
			camera_location = self.selected_camera, 
			location = self.location 
		})

		-- check if the player is now looking at this character in a hallway while fully evolved
		check_hallway(self)

	elseif message_id == hash("update_camera_status") then

		-- update this character's variable tracking if the cameras are visible
		self.is_in_camera = message.is_in_camera

		-- update whether this character is visible
		msg.post(".", "update_visibility", {
			is_in_camera = self.is_in_camera, 
			camera_location = self.selected_camera, 
			location = self.location 
		})

		-- check if the player is now looking at this character in a hallway while fully evolved
		check_hallway(self)
		
	elseif message_id == hash("update_doors") then
		-- update the values for which doors are open and which are closed
		self.doors_closed[message.selected_door] = message.is_closed
		-- print(self.name .. " has been told " .. message.selected_door .. " door is now closed: " .. tostring(message.is_closed))
		-- print(self.name .. " thinks " .. message.selected_door .. " door is now closed: " .. tostring(self.doors_closed[message.selected_door]))

		-- update door timers if this character is in the office and the door that opened/closed was the one he's at
		if message.selected_door == self.my_path then
			set_door_timers(self)
		end

	end
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
