-- import the shared helper functions
local cu = require "scripts.character_scripts.character_utils"


local function toggle_visibility(self, selected_camera, is_in_camera)
	-- function to make the dummy visible or invisible and move
	-- it to the given side of the office
	-- @param self: allows this function to access self.<variable> variables
	-- @param selected_camera: str, indicates what camera the player has selected
	-- @param is_in_camera: bool, indicates whether the player is in the camera or the office
	-- @return: nothing

	-- get the player's view
	local player_view = cu.get_player_view(is_in_camera, selected_camera)

	-- figure out if the player is looking at this prop's camera
	local is_visible = player_view == self.location

	-- get the position on the correct side of the office
	local curr_position = go.get_position()

	-- get the correct z coordinate based on if the dummy needs to be visible or invisible
	local bool_to_z = {
		[true] = 0.5,
		[false] = 100
	}

	-- move the sprite to the x,y coords indicated by 'side' and the z-coord to make it visible
	go.set_position(vmath.vector3(curr_position.x, curr_position.y, bool_to_z[is_visible]))
	print(self.name .. " in camera has visibility status: " .. tostring(is_visible))

end


function init(self)
	-- Add initialization code here

	-- initialize the variable storing the name of the character whose sprite this dummy uses
	self.name = "prop"

	-- initialize the variable for this prop's url
	self.url = "/camera/rotom/prop"

	-- initialize a variable storing this prop's location
	self.location = "Cam 01"

	-- initialize a variable tracking this prop's default sprite
	self.default_sprite = "none"

	-- initialize a variable tracking whether the player is in the camera
	self.is_in_camera = false

	-- initialize a variable tracking what camera the player has selected
	self.selected_camera = "Cam 01"

	-- become invisible
	toggle_visibility(self, self.selected_camera, self.is_in_camera)

	-- initialize boolean tracking if the challenge mode is on
	self.is_tera = false

	-- initialize the boolean tracking if this prop is possessed by rotom
	self.is_possessed = false
end


local function start_night(self)
	-- Add code that resets this prop to behave correctly when the night starts

	-- initialize a variable tracking whether the player is in the camera
	self.is_in_camera = false

	-- initialize a variable tracking what camera the player has selected
	self.selected_camera = "Cam 01"

	-- become invisible
	toggle_visibility(self, self.selected_camera, self.is_in_camera)

	-- set this prop to its default sprite
	sprite.play_flipbook(self.url, self.default_animation)

	-- acquire input focus
	msg.post(".", "acquire_input_focus")

	-- set this prop's hitbox to the appropriate visibility
	if self.hitbox_visible and self.level > 0 then
		for _, hitbox_url in ipairs(self.hitboxes) do
			-- set hitbox sprite's alpha to 0.5
			go.set(hitbox_url, "tint.w", 0.5)
		end
	else
		for _, hitbox_url in ipairs(self.hitboxes) do
			-- set hitbox sprite's alpha to 0
			print(self.name .. ": attempting to access hitbox url: " .. hitbox_url)
			go.set(hitbox_url, "tint.w", 0)
		end
	end

end


function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end


function on_message(self, message_id, message, sender)
	-- Add message-handling code here

	print(self.name .. " prop in " .. self.location .. " received a message: " .. message_id .. " from sender:" .. sender)
	pprint(message)
	if message_id == hash("define_self") then
		-- this message indicates what this prop's name is
		self.name = message.name

		-- initialize a list of the urls for this character's hitboxes
		self.hitboxes = { self.name .. "_hitbox#sprite" }
		self.hitbox_visible = false

		-- this message indicates what this prop's url is too
		self.url = message.url

		-- this message also tells the prop what camera it's in
		self.location = message.location

		-- this message also defines the prop's default animation
		self.default_animation = message.animation

	elseif message_id == hash("new_night") then
		-- run the function that resets all timers and variables for the start of a new night
		start_night(self)

		self.is_tera = message.is_tera
		self.hitbox_visible = message.hitboxes_enabled

	elseif message_id == hash("change_camera_location") then

		-- update this character's variable tracking what camera the player has selected
		self.selected_camera = message.new_cam

		-- update whether this prop is visible
		toggle_visibility(self, self.selected_camera, self.is_in_camera)

	elseif message_id == hash("update_camera_status") then

		-- update this character's variable tracking if the cameras are visible
		self.is_in_camera = message.is_in_camera

		-- update whether this character is visible
		toggle_visibility(self, self.selected_camera, self.is_in_camera)

	elseif message_id == hash("animate_prop") then

		print("animation name: " .. message.animation_name)
		-- this message plays the named animation
		sprite.play_flipbook("#" .. self.name .. "_sprite", message.animation_name, function()
			print("successfully finished playing animation: " .. message.animation_name)
			-- check if this prop needs to return to its default animation when done
			if message.return_when_done then
				-- return to this prop's default animation when done
				sprite.play_flipbook(self.url, self.default_animation)
			end
		end)

	elseif message_id == hash("end_night") then
		-- release input focus at end of night
		msg.post(".", "release_input_focus")

	elseif message_id == hash("disable_camera") then
		-- this lets the character know if a camera is disabled while they're on it
		if self.location == message.camera_location then
			msg.post(".", "release_input_focus")
		end

	elseif message_id == hash("update_possession") then
		-- update the boolean indicating if rotom's possessing this prop
		self.is_possessed = message.is_possessed
	end
end


local function check_hitbox(self, x, y)
	-- function to check, when the mouse was clicked, if this character's hitbox was clicked
	-- @param self: grants access to self.<variable> namespace
	-- @param x: float, x position of the mouse click
	-- @param y: float, y position of the mouse click
	-- @return: true if the hitbox was clicked (could be modded to return name of hitbox)

	print("Click at (" .. tostring(x) .. ", " .. tostring(y) .. "), " .. self.name .. " sees: ")

	-- iterate through all hitboxes for this character
	for _, hitbox_url in ipairs(self.hitboxes) do
		-- pretend that the hitbox is on the same z position as the mouse
		local hitbox_xy = go.get_world_position(hitbox_url)
		hitbox_xy.z = 0

		local distance = vmath.length(vmath.vector3(x, y, 0) - hitbox_xy)

		local hitbox_size = go.get(hitbox_url, "size")
		print("distance to " .. hitbox_url .. " is " .. tostring(distance) .. " and hitbox is " .. tostring(hitbox_size.x) .. " pixels wide")

		-- check if the distance to the current hitbox is close enough
		local is_visible = self.location == cu.get_player_view(self.is_in_camera, self.selected_camera)

		-- NOTE: can replace this with a self.is_clicked parameter (this makes the kill timer redundant)
		local is_clicked = timer.get_info(self.kill_timer) == nil

		-- NOTE: this distance check makes hitboxes functionally circular 
		-- because it calculates based on the coords for the center of the hitbox
		if distance <= hitbox_size.x / 2 and is_visible and not is_clicked then
			print(self.name .. " has determined that " .. hitbox_url .. " has been clicked")
			return true
		end
	end

	-- if we made it here, then none of the hitboxes evaluated as being clicked
	print(self.name .. " determined that none of its hitboxes were clicked")
	return false
end


function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus

	if action_id == hash("mouse1")  and action.released then
		-- check if a camera button's node was clicked, and update cameras if yes
		local hitbox_clicked = check_hitbox(self, action.x, action.y)
		if hitbox_clicked and self.is_possessed then
			print(self.name .. ": hitbox clicked while possessed")
			-- tell rotom the sprite was clicked
			msg.post("/camera/rotom", "hitbox_clicked", { prop_name = self.name })
			-- get the name of the animation to play
			-- local animation_to_play = self.name .. "_clicked_possessed_tera" and self.is_tera or self.name .. "_clicked_possessed"
			sprite.play_flipbook("#" .. self.name .. "_sprite", self.default_animation) -- TODO: change to animation_to_play

		elseif hitbox_clicked and not self.is_possessed then
			print(self.name .. ": hitbox clicked while not possessed")
			-- just play the animation for when the prop gets clicked without being possessed
			sprite.play_flipbook("#" .. self.name .. "_sprite", self.default_animation) -- TODO: change to self.name .. "_clicked"
		end

	end
end
