-- import the shared helper functions
local cu = require "scripts.character_scripts.character_utils"

-- forward-declare the driver function so it can be mutually recurred by restart_path()
local driver

-- initialize AI level
go.property("level", 0)

-- initialize movement interval
go.property("interval", 15)

-- initialize if the player is in the challenge mode
go.property("is_tera", false)


function init(self)
	-- Add initialization code here

	-- initialize character name
	self.name = "ursaluna"

	-- initialize his location on screen
	self.location = "Cam 03"

	-- initialize the list of locations in this character's path (he only has one path)
	self.path = {"Cam 03", "Cam 01", "Cam 02", "Cam 04", "Cam 05", "Cam 09", "office"}

	-- initialize a variable tracking which path the character is on (used to track which door needs to be closed
	-- and to track which side of the office the minimap needs to place his icon on)
	self.my_path = "left"

	-- initialize a variable tracking what step of his path he's on
	self.movement_step = 1

	-- initialize the dictionary mapping camera locations to his position on screen
	self.position_dict = {
		["Cam 01"] = vmath.vector3(-157.0, -87.0, 0.0),
		["Cam 02"] = vmath.vector3(-276.0, 116.0, 0.0),
		["Cam 03"] = vmath.vector3(-276.0, 116.0, 0.0),
		["Cam 04"] = vmath.vector3(-321.0, -213.0, 0.0),
		["Cam 05"] = vmath.vector3(0, 0, 0.0),
		["Cam 09"] = vmath.vector3(0, 0, 0.0),
		["office"] = vmath.vector3(0, 0, 0.0)  -- note that this one doesn't matter this character won't be visible from the door
	}
	
	-- initialize the dictionary mapping camera locations to this character's sprite names
	self.sprite_dict = {
		["Cam 01"] = "ursaluna",
		["Cam 02"] = "ursaluna",
		["Cam 03"] = "ursaluna",
		["Cam 04"] = "ursaluna",
		["Cam 05"] = "ursaluna",
		["Cam 09"] = "ursaluna",
		["office"] = "ursaluna"  -- note that this one doesn't matter because this character won't be visible in the door
	}

	-- initialize values to track if the player is in the cameras
	self.is_in_camera = false

	-- initialize a value to track which camera is currently selected
	self.selected_camera = "Cam 01"

	-- initialize a value to know if the character's curent location in the camera is enabled/disabled
	self.cam_enabled = true

	-- initialize variables to know if either door is open
	self.doors_closed = {
		right = false, 
		left = false
	}

	-- initialize all timers
	self.movement_timer = timer.delay(0, false, function() print(self.name .. ": move timer initialized") end)
	self.door_timer = timer.delay(0, false, function() print(self.name .. ": door timer initialized") end)
	self.look_timer = timer.delay(0, false, function() print(self.name .. ": look timer initialized") end)
	self.kill_timer = timer.delay(0, false, function() print(self.name .. ": kill timer initialized") end)
	
	-- become invisible
	local curr_position = go.get_position()
	go.set_position(vmath.vector3(curr_position.x, curr_position.y, 100))

	-- initialize the variable tracking how much time this character should wait at the door
	self.max_door_time = 0.5

	-- initialize the variable tracking how much time this character has left to wait at the door
	self.remaining_door_time = self.max_door_time

	-- initialize the variable tracking how much time this character's kill timer has left on it
	self.remaining_kill_time = 5

	-- initialize the variable tracking how much time is left on the current movement
	self.remaining_move_time = self.interval

	-- initialize the variable for how much time should be added to Ursaluna's movement timer for each second spent watching him
	self.watchtime_multiplier = 3

	-- post a message to the instance of shared_character_code attached to this character
	-- informing it of which character's properties it should read
	msg.post(".", "define_self", { name = self.name })
end


local function add_move_time(self, time_to_add)
	-- function to increase the time left on this character's move timer while being watched
	-- this function is run by a looping timer that runs every 0.1 seconds
	-- so ursaluna adds X seconds to the move timer time per 1.0 seconds spent looking at him
	-- @param self: grants access to self.<variable> namespace
	-- @return: nothing, just sets a timer and aliases in the self.<variable> namespace
	
	-- add 0.05 seconds to the door timer
	self.remaining_move_time = self.remaining_move_time + (0.1 * self.watchtime_multiplier)

	print(self.name .. ": move time increased to " .. self.max_door_time)

	-- send a message to the gui to update how much time this character's door time has on it
	msg.post(".", "update_displayed_time", {timer_name = "move_time", time_remaining = self.remaining_move_time, is_running = false})
	
	print(self.location)

end

-- despite being VERY similar to the one in character_utils.lua, this one has to stay
-- because of the code for Ursaluna's mechanic being called in this function
local function update_visibility(self)
	-- function to determine if this character should be visible on screen
	-- @param self: allows this function to access self.<variable> variables
	-- @return: nothing, just runs functions to either make the character visible or invisible

	-- determine what the player is looking at
	local player_location = cu.get_player_view(self.is_in_camera, self.selected_camera)
	print(self.name .. ": thinks the player is looking at: " .. player_location)

	-- check if the current camera is disabled
	-- msg.post("/camera_GUI", "is_cam_enabled", { camera = self.locations })
	-- TODO: if combo with abra is problematic, uncomment this and re-add "and self.cam_enabled" to following if statement

	-- have a check to allow Ursaluna to show up in the hallway camera to show that he's right at the door
	local is_at_hall_door = (self.location == "office") and (player_location == "Cam 09")
	
	-- check if this character is in the location the player is i
	if self.location == player_location or is_at_hall_door then

		-- make the character become visible
		cu.become_visible(go, vmath)

		print(self.name .. ": is now visible at " .. self.location)

		-- pause the movement timer
		self.remaining_move_time = cu.pause_timer(self.movement_timer, timer)
		print(self.name .. ": printing results of timer.get_info on movement timer")
		pprint(timer.get_info(self.movement_timer))
		
		-- set a looping timer that adds time back onto the movement timer
		self.look_timer = timer.delay(0.1, true, add_move_time)

	else

		-- make the character become invisible
		cu.become_invisible(go, vmath)

		print(self.name .. ": is now invisible at " .. self.location)

		-- check if the movement timer is running
		local result = timer.get_info(self.movement_timer)
		print(self.name .. ": result of timer.get_info on movement_timer: ")
		pprint(result)

		if result == nil then
			-- we know that the movement timer needs to be restarted

			-- stop adding time to the move timer
			result = timer.cancel(self.look_timer)
			print("Result of cancelling " .. self.name .. "'s look timer: " .. tostring(result))

			-- restart the movement timer with however much time is left on it
			self.movement_timer = timer.delay(self.remaining_move_time, false, driver)
			msg.post(".", "update_displayed_time", {timer_name = "move_time", time_remaining = self.remaining_move_time, is_running = true})
			print(self.name .. ": move time is: " .. self.remaining_move_time)
		end
	end

end


local function progress_movement(self)
	-- function to increment the character's movement step and update their
	-- location and position accordingly
	-- @param self: 
	-- @return: nothing probably

	-- add 1 to the character's movement step
	self.movement_step = self.movement_step + 1

	-- update the character's location
	-- access the right room in the list by keying it with the current step of 
	-- this character's movement progression
	self.location = self.path[self.movement_step]
	print(self.name .. ": moved to " .. self.location .. " along " .. self.my_path .. " path")

	-- tell the camera GUI to move this character's icon on the minimap (only visible if radar is on)
	msg.post("/camera_GUI", "move_character", 
		{char_name = self.name, 
		new_pos = self.location, 
		side = self.my_path
	})

	-- have this character check if they're visible
	update_visibility(self)

	-- update this character's position on screen
	cu.update_coords(self.position_dict, self.location, go)
	
end


local function cancel_all_timers(self)
	-- function to cancel all of this character's timers
	-- @param self:
	-- @return: nothing, just cancels timers

	timer.cancel(self.movement_timer)
	timer.cancel(self.door_timer)
	timer.cancel(self.look_timer)
	timer.cancel(self.kill_timer)

end


local function attack_door(self)
	-- function to check if the door is closed, and kills the player if not
	print("kill player ran, " .. self.my_path .. " door is closed: " .. tostring(self.doors_closed[self.my_path]))
	-- check if the door is closed
	if not self.doors_closed[self.my_path] then
		-- if the door isn't closed, start by playing the sound for the jumpscare
		cu.play_directional_sound(sound, "#" .. self.name .. "_cry")

		-- send a message to the office gui to kill the player
		msg.post("/office_GUI", "kill_player", { character_name = self.name })
		
		-- cancel this character' timers
		cancel_all_timers(self)
	end
	
end


local function enter_kill_state(self)
	-- function to set a timer that is used to determine if this character
	-- should kill the player while this character is in the office
	-- @param self:
	-- @return: none, sets timers and maps them to self.<variable> variables

	-- for debugging reasons, attempt to stop an existing kill timer
	local result = timer.cancel(self.kill_timer)
	print(self.name .. ": attempting to cancel the kill timer before starting new one. Old ID is " .. self.kill_timer .. " and result of cancelling is: " .. tostring(result))

	-- set the initial timer for the character appearing in the door before being a threat
	self.kill_timer = timer.delay(self.interval, false, attack_door)
	msg.post(".", "update_displayed_time", {timer_name = "kill_time", time_remaining = self.interval, is_running = true})

end


local function restart_path(self)
	-- function to reset this character's movement path 
	
	-- reset movement to step 0
	self.movement_step = 0
	-- go to the first room in the path (this function will increment the movement step to 1, which is the 
	-- show stage in both paths)
	progress_movement(self)
	-- recalculate this character's movement interval
	self.interval = cu.calculate_interval(self.non_random, math)
	msg.post(".", "update_displayed_time", {timer_name = "move_time", time_remaining = self.interval, is_running = true})
	-- start the timer for the next movement
	self.movement_timer = timer.delay(self.interval, false, driver)

	print(self.name .. ": just moved to " .. self.location .. "; New interval = " .. self.interval .. " sec")
end


local function leave_kill_state(self)
	-- function to handle this character leaving their kill state at the door
	-- Includes: cancelling door timer and kill timer, resetting position variable
	-- picking a new movement path, and restarting the movement timer
	-- @param self:
	-- @return: nothing, just cancels a timer

	-- reset this character's kill timer
	self.remaining_kill_time = self.interval

	-- cancel this character's kill timer
	local result = timer.cancel(self.kill_timer)
	print("Leaving kill state, Result of cancelling " .. self.name .. "'s kill timer: " .. tostring(result))

	-- cancel this character's timer to leave the door
	result = timer.cancel(self.door_timer)
	print("Leaving kill state, Result of cancelling " .. self.name .. "'s door timer: "  .. tostring(result))
	self.remaining_door_time = self.max_door_time
	msg.post(".", "update_displayed_time", {timer_name = "door_time", time_remaining = self.max_door_time, is_running = false})

	-- play the sound effect for leaving the door
	cu.play_directional_sound(sound, "#door_bonk", self.my_path, 1.00)

	-- use message passing to call the driver function because it's not defined yet at the time
	-- of this function getting compiled
	restart_path(self)

end


function driver(self)
	-- driver function to be called by the timer

	-- move to the next location
	progress_movement(self)

	-- check if the character is in the office
	if self.location == "office" and not self.doors_closed[self.my_path] then
		-- run the function for the character to enter his kill state at the door
		print(self.name .. ": Reached office, door was open. Entering kill state.")
		enter_kill_state(self)

		-- check if the door is closed when the character gets there
	elseif self.location == "office" and self.doors_closed[self.my_path] then
		-- set the door timer to leave the kill state if the door stays closed
		print(self.name .. "Reached office, door was closed. Starting door timer: " .. self.remaining_door_time .. " seconds")
		self.door_timer = timer.delay(self.remaining_door_time, false, leave_kill_state)
		msg.post(".", "update_displayed_time", {timer_name = "door_time", time_remaining = self.remaining_door_time, is_running = true})
		
	else

		-- update this character's sprite
		cu.update_sprite(self.name, self.sprite_dict, self.location, sprite)

		-- update this character's movement interval
		self.interval = cu.calculate_interval(self.non_random, math)
		msg.post(".", "update_displayed_time", {timer_name = "move_time", time_remaining = self.interval, is_running = true})

		-- reset the time remaining on the current movement
		self.remaining_move_time = self.interval

		-- for debugging reasons, attempt to stop an existing movement timer
		local result = timer.cancel(self.movement_timer)
		print(self.name .. ": attempting to cancel the move timer before starting new one. Old ID is " .. self.movement_timer .. " and result of cancelling is: " .. tostring(result))

		-- start the timer for the next movement
		-- this is recursive, but can be broken if the timer is canceled
		self.movement_timer = timer.delay(self.interval, false, driver)

	end

	print(self.name .. ": just moved to " .. self.location .. "; New interval = " .. self.interval .. " sec")
end


local function set_door_timers(self)
	-- function to check if this character is in the office when a door is closed
	-- and either start or cancel this character's door timer (depending on whether
	-- the door this character is at has been opened or closed)

	-- make a couple booleans to shorten the next if statements
	local is_in_office = self.location == "office"
	local my_door_closed = self.doors_closed[self.my_path]

	print("set_door_timers ran: is_in_office = " .. tostring(is_in_office) .. " // my_door_closed = " .. tostring(my_door_closed))

	-- check if this character's door is closed
	if is_in_office and my_door_closed then
		-- this runs if the door this character is at was closed
		-- and only if the door timer isn't running

		-- start a counter to leave the door when it's been closed for half a second
		self.door_timer = timer.delay(self.remaining_door_time, false, leave_kill_state)
		print(self.name .. ": is in office and door is closed, starting door time pie node animation")
		msg.post(".", "update_displayed_time", {timer_name = "door_time", time_remaining = self.remaining_door_time, is_running = true})
		
		-- pause the kill timer
		local remaining_kill_time = cu.pause_timer(self.kill_timer, timer)

		-- check if the pause function returned a nil value
		if remaining_kill_time then
			-- only overwrite the remaining kill time if the kill timer was successfully paused
			self.remaining_kill_time = remaining_kill_time
			msg.post(".", "update_displayed_time", {timer_name = "kill_time", time_remaining = self.remaining_kill_time, is_running = false})
			
		end
		
		print(self.name .. ": Door closed, result of cancelling kill timer: " .. tostring(remaining_kill_time) .. ". " .. self.remaining_kill_time .. " sec left on it")

	elseif is_in_office and not my_door_closed then
		-- this runs if the door this character was at was opened while he was there
		-- and only if the kill timer has been paused

		-- pause the door timer
		local remaining_door_time = cu.pause_timer(self.door_timer, timer)

		-- check if the pause function returned a nil value
		if remaining_door_time then
			-- only overwrite the remaining door time if the pause function returned a number for the amount of time remaining
			self.remaining_door_time = remaining_door_time
			print("Resuming door timer pie animation")
			msg.post(".", "update_displayed_time", {timer_name = "door_time", time_remaining = self.remaining_door_time, is_running = false})
			
		end
		
		print(self.name .. ": Door opened, result of cancelling door timer: " .. tostring(remaining_door_time).. ". " .. self.remaining_door_time .. " seconds left on it")

		print(self.name .. ": Restarting kill timer with " .. self.remaining_kill_time .. " sec remaining.")
		-- resume the kill timer
		self.kill_timer = timer.delay(self.remaining_kill_time, false, attack_door)
		msg.post(".", "update_displayed_time", {timer_name = "kill_time", time_remaining = self.remaining_kill_time, is_running = true})
		

	end

end


function final(self)
	-- Add finalization code here
	cancel_all_timers(self) --putting this here so we don't accidentally cause memory leaks
end


local function start_night(self)
	-- function to reset all variables, timers, and sprites when the night starts
	-- @param self: 
	-- @return: nothing, just resets self.<variable> variables, sprites, position, and timers

	-- reset movement interval
	self.non_random = cu.calculate_nonrandom_interval(self.level, 10, 75)
	self.interval = cu.calculate_interval(self.non_random, math)
	msg.post(".", "update_displayed_time", {timer_name = "move_time", time_remaining = self.interval, is_running = self.level ~= 0})
	

	-- reset his location on screen
	self.location = "Cam 03"

	-- reset he variable tracking what step of his path he's on
	self.movement_step = 1

	-- reset values to track if the player is in the cameras
	self.is_in_camera = false

	-- reset the value indicating if the current location in the cameras is enabled/disabled
	self.cam_enabled = true

	-- reset the value to track which camera is currently selected
	self.selected_camera = "Cam 01"

	-- reset the variable tracking how much time this character has left to wait at the door
	self.remaining_door_time = self.max_door_time

	-- reset the variable tracking how much time this character's kill timer has left on it
	self.remaining_kill_time = 5

	-- reset the variable tracking how much time is left on the current movement
	self.remaining_move_time = self.interval

	-- reset the variable for how much time should be added to Ursaluna's movement timer for each second spent watching him
	self.watchtime_multiplier = 3

	-- send the door time and kill time to the office GUI
	msg.post(".", "update_displayed_time", {timer_name = "door_time", time_remaining = self.max_door_time, is_running = false})
	msg.post(".", "update_displayed_time", {timer_name = "kill_time", time_remaining = self.remaining_kill_time, is_running = false})
	

	-- tell the camera GUI to move the this character icon on the minimap (only visible if radar is on)
	msg.post("/camera_GUI", "move_character", 
	{char_name = self.name, 
	new_pos = self.location, 
	side = self.my_path
	})

	-- reset variables to know if either door is open
	self.doors_closed = {
		right = false, 
		left = false
	}

	-- reset this character's position
	go.set_position(self.position_dict[self.location])

	-- become invisible for the start of the night
	update_visibility(self)

	-- reset sprite
	sprite.play_flipbook("#" .. self.name .. "_sprite", self.sprite_dict[self.location])

	-- check if this character's AI level is above 0
	if self.level ~= 0 then

		-- start the timer for a new night if the character's level is above 0
		print(self.name .. "'s initial interval: " .. self.interval)
		self.movement_timer = timer.delay(self.interval, false, driver)
	end
	

end


function on_message(self, message_id, message, sender)
	-- Add message-handling code here

	print(self.name .. ": received a message: " .. message_id .. " from sender:" .. sender)
	-- pprint(message)

	if message_id == hash("new_night") then
		-- update this character's AI level
		self.level = message.ai_level
		print(self.name .. ": set to level " .. self.level)
		
		-- update whether the challenge mode is active
		self.is_tera = message.is_tera
		print(self.name .. ": thinks tera mode is on: " .. tostring(self.is_tera))

		-- reset the variable tracking how much time this character should wait at the door,
		-- implementing this character's tera mechanic of "never" leaving the door
		if self.is_tera then
			self.max_door_time = 10000
		else
			self.max_door_time = 0.5
		end

		-- run the function that resets all timers and variables for the start
		-- of a new night
		start_night(self)

	elseif message_id == hash("end_night") then
		-- cancel all timers
		cancel_all_timers(self)

	elseif message_id == hash("change_camera_location") then

		-- update this character's variable tracking what camera the player has selected
		self.selected_camera = message.new_cam

		-- update whether this character is visible
		update_visibility(self)

	elseif message_id == hash("update_camera_status") then

		-- update this character's variable tracking if the cameras are visible
		self.is_in_camera = message.is_in_camera

		-- update whether this character is visible
		update_visibility(self)
		
	elseif message_id == hash("update_doors") then
		-- update the values for which doors are open and which are closed
		self.doors_closed[message.selected_door] = message.is_closed
		print(self.name .. ": has been told " .. message.selected_door .. " door is now closed: " .. tostring(message.is_closed))
		print(self.name .. ": thinks " .. message.selected_door .. " door is now closed: " .. tostring(self.doors_closed[message.selected_door]))

		-- update door timers if this character is in the office and the door that opened/closed was the one he's at
		if message.selected_door == self.my_path then
			set_door_timers(self)
		end

	elseif message_id == hash("is_cam_enabled") then
		-- camera GUI has responded with whether this character's location in the cams is enabled/disabled
		if message.is_enabled then
			self.cam_enabled = true
		else
			self.cam_enabled = false
		end

	end
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
